#!/usr/bin/env python3

#This is amazing way to write the quick sort method.

def quickSort(arr):
	if len(arr) <= 1:
		return arr
	else:
		return quickSort( [x for x in arr[1:] if x < arr[0]]) + [arr[0]]+quickSort([x for x in arr[1:] if x>=arr[0]])

print quickSort([3,1,4,1,5,9,2,6,5])
